'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_branch: main
          dst_branch: main
          src_path: /.
          dst_path: /.
          dst_owner: nickopicazo
          dst_repo_name: test-uk
          exclude: '*{**/.github/*,**/.git/*,*.json,*.toml}'
          commit_message: "[CI] Deployment"
